apiVersion: v1
kind: Service
metadata:
  name: strategy
spec:
  selector:
    app: strategy
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: strategy      
  template:
    metadata:
      labels:
        app: strategy
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      initContainers:
        - name: wait-for-nats
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z nats 4222; do echo waiting for nats; sleep 2; done;']
      containers:
        - name: strategy
          image: {{ .Values.images.strategy }}
          ports:
            - containerPort: 80
          env:
            - name: NATS_URL
              value: "{{ .Values.env.strategy.NATS_URL }}"
            - name: NATS_USER
              value: "{{ .Values.env.nats.USER }}"
            - name: NATS_PASS
              value: "{{ .Values.env.nats.PASS }}"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"